// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:06bc3232-ab1b-4a41-8da9-8bcbe02f0dc6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_l8G4lrYIC",
    "aws_user_pools_web_client_id": "45f0cg51crj1agc4tk6usgiu3a",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://awfckoteibfnnpce7dfdnj4sle.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
